steps:
- name: 'gcr.io/cloud-builders/git'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      git init
      git remote add origin https://github.com/Metatavu/muisti-exhibition-ui.git
      git fetch --depth=1 origin $COMMIT_SHA
      git reset --hard FETCH_HEAD
      git submodule update --init
      ls -lha

- name: amazon/aws-cli
  args: ["configure", "set", "aws_access_key_id", "$_AWS_ACCESS_KEY_ID"]
- name: amazon/aws-cli
  args: ["configure", "set", "aws_secret_access_key", "$_AWS_SECRET_ACCESS_KEY"]
- name: ubuntu
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      apt update
      apt install golang-go -y
      apt install docker -y
      go get -u github.com/omerh/aws-docker-login
      $(aws-docker-login $_AWS_DEFAULT_REGION)
- name: 'gcr.io/kubernetes-240206/android-build-docker:master'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
       ./gradlew clean build
  env:
    - 'ANDROID_SDK_ROOT=/usr/lib/android-sdk'
    - 'ANDROID_HOME=/usr/lib/android-sdk'

timeout: 6001s
