steps:
- name: 'gcr.io/cloud-builders/git'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      git init
      git remote add origin https://github.com/Metatavu/muisti-exhibition-ui.git
      git fetch --depth=1 origin $COMMIT_SHA
      git reset --hard FETCH_HEAD
      git submodule update --init
      ls -lha      
- name: gcr.io/$PROJECT_ID/remote-builder
  env:
    - USERNAME=root
    - ZONE=us-central1-b
    - COMMAND=ls -la
    - INSTANCE_ARGS=--zone us-central1-b --image-project=$PROJECT_ID --image=android-build-rev1
