steps:
- name: 'gcr.io/cloud-builders/git'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
      git init
      git remote add origin git@github.com:/Metatavu/muisti-exhibition-ui.git
      git fetch --depth=1 origin $COMMIT_SHA
      git reset --hard FETCH_HEAD
      git submodule update --init
- name: 'gcr.io/kubernetes-240206/android-build-docker:master'
  args: ["./gradlew", "clean", "build", "test"]

