steps:

- name: 'gcr.io/cloud-builders/git'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      git init
      git remote add origin https://github.com/Metatavu/muisti-exhibition-ui.git
      git fetch --depth=1 origin $COMMIT_SHA
      git reset --hard FETCH_HEAD
      git submodule update --init
      ls -lha

- name: amazon/aws-cli
  args: ["configure", "set", "aws_access_key_id", "$_AWS_ACCESS_KEY_ID"]
- name: amazon/aws-cli
  args: ["configure", "set", "aws_secret_access_key", "$_AWS_SECRET_ACCESS_KEY"]
- name: amazon/aws-cli
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      aws ecr get-login-password --region $_AWS_DEFAULT_REGION > ~/password.txt
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      cat ~/password.txt | docker login --username AWS --password-stdin $_AWS_ECR_URL
- name: 'gcr.io/kubernetes-240206/android-build-docker:master'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      ./gradlew clean build
  volumes:
  - name: 'supervisorlogs'
    path: '/var/log/supervisor'
  env:
    - 'ANDROID_SDK_ROOT=/usr/lib/android-sdk'
    - 'ANDROID_HOME=/usr/lib/android-sdk'
- name: 'gcr.io/cloud-builders/docker'
  waitFor: ["-"]
  volumes:
  - name: 'supervisorlogs'
    path: '/var/log/supervisor'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      sleep 10m
      docker exec -it $(docker ps -aq) tail -f /var/log/supervisor/docker-android.stdout.log
artifacts:
  objects:
    location: 'gs://metatavu-cloud-build-logs/$PROJECT_ID/$BUILD_ID'
    paths: ['/var/log/supervisor']
options:
  machineType: 'N1_HIGHCPU_8'
timeout: 6001s
