steps:
- name: 'gcr.io/cloud-builders/git'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      git init
      git remote add origin https://github.com/Metatavu/muisti-exhibition-ui.git
      git fetch --depth=1 origin $COMMIT_SHA
      git reset --hard FETCH_HEAD
      git submodule update --init
      ls -lha
- name: amazon/aws-cli
  args: ["ecr", "get-login-password", "--no-include-email", "--region", "$_AWS_DEFAULT_REGION"]
- name: 'gcr.io/kubernetes-240206/android-build-docker:master'
  args: ["./gradlew", "clean", "build"]
  env:
    - 'ANDROID_SDK_ROOT=/usr/lib/android-sdk'
    - 'ANDROID_HOME=/usr/lib/android-sdk'

timeout: 6000s
