steps:
- name: gcr.io/$PROJECT_ID/remote-builder
  env:
    - ZONE=us-central1-b
    - COMMAND=ls -la
    - INSTANCE_ARGS=--zone us-central1 --min-cpu-platform Intel Haswell --image-project=$PROJECT_ID --image=android-build-rev1
