version: "3"
services:
  keycloak-mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: password
  muisti-api-mysql:
    image: mysql:5.7
    command: --lower_case_table_names=1
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: muisti-api
      MYSQL_USER: muisti-api
      MYSQL_PASSWORD: password
  test-keycloak:
    image: jboss/keycloak:8.0.1
    environment:
      DB_VENDOR: MYSQL
      DB_ADDR: keycloak-mysql
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: password
      JDBC_PARAMS: "verifyServerCertificate=false&useSSL=false"
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_IMPORT: /opt/docker/kc.json
    ports:
      - 8080:8080
    depends_on:
      - keycloak-mysql
    volumes:
      - ./test-volumes/keycloak:/opt/docker
  test-mqtt:
    image: eclipse-mosquitto
    ports:
      - 1883:1883
  muisti-api:
    image: 414711980085.dkr.ecr.eu-central-1.amazonaws.com/muisti-api:latest
    ports:
      - 1234:8080
    depends_on:
      - muisti-api-mysql
      - test-keycloak
      - test-mqtt
    environment:
      API_HOST: localhost
      API_CLUSTER_PASSWORD: 4a0fc96f-c8d4-45c9-af69-4b7edd62df0d
      API_DB_HOST: muisti-api-mysql
      API_DB_NAME: muisti-api
      API_DB_USERNAME: muisti-api
      API_DB_PASSWORD: password
      KEYCLOAK_SECRET: a1d94fb9-0f35-42e8-a56a-001ffab13e6e
      KEYCLOAK_REALM: muisti
      KEYCLOAK_RESOURCE: api
      KEYCLOAK_URL: http://test-keycloak:8080/auth
      KUBERNETES_NAMESPACE: test
      FILE_STORAGE_PROVIDER: LOCAL
      LOCAL_FILE_STORAGE_PATH: /opt/uploads
      MQTT_SERVER_URL: test-mqtt
      MQTT_TOPIC: test
    volumes:
      - ./test-volumes/uploads:/opt/uploads
  docker-android:
    image: budtmo/docker-android-x86-10.0:latest
    ports:
      - 6080:6080
      - 5554:5554
      - 5555:5555
      - 4723:4723
    environment:
      DEVICE: Samsung Galaxy S9
      APPIUM: "true"
    privileged: true
    volumes:
      - ./app/build/outputs/apk/debug:/root/tmp
      - /var/log/supervisor/:/var/log/supervisor/

