/**
* Muisti API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package fi.metatavu.muisti.api.client.models


import com.squareup.moshi.Json
/**
 * 
 * @param id 
 * @param name 
 * @param creatorId 
 * @param lastModifierId 
 * @param createdAt Created date
 * @param modifiedAt Date modified
 */

data class Exhibition (
    @Json(name = "name")
    val name: kotlin.String,
    @Json(name = "id")
    val id: java.util.UUID? = null,
    @Json(name = "creatorId")
    val creatorId: java.util.UUID? = null,
    @Json(name = "lastModifierId")
    val lastModifierId: java.util.UUID? = null,
    /* Created date */
    @Json(name = "createdAt")
    val createdAt: kotlin.String? = null,
    /* Date modified */
    @Json(name = "modifiedAt")
    val modifiedAt: kotlin.String? = null
) 



