/**
* Muisti API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package fi.metatavu.muisti.api.client.models

import fi.metatavu.muisti.api.client.models.VisitorSessionState
import fi.metatavu.muisti.api.client.models.VisitorSessionUser
import fi.metatavu.muisti.api.client.models.VisitorSessionVariable

import com.squareup.moshi.Json
/**
 * 
 * @param id Unique id for the session
 * @param exhibitionId Exhibition id the visiotr was attending to
 * @param state 
 * @param variables 
 * @param users 
 * @param creatorId 
 * @param lastModifierId 
 * @param createdAt Created date
 * @param modifiedAt Date modified
 */

data class VisitorSession (
    @Json(name = "users")
    val users: kotlin.Array<VisitorSessionUser>,
    /* Unique id for the session */
    @Json(name = "id")
    val id: java.util.UUID? = null,
    /* Exhibition id the visiotr was attending to */
    @Json(name = "exhibitionId")
    val exhibitionId: java.util.UUID? = null,
    @Json(name = "state")
    val state: VisitorSessionState? = null,
    @Json(name = "variables")
    val variables: kotlin.Array<VisitorSessionVariable>? = null,
    @Json(name = "creatorId")
    val creatorId: java.util.UUID? = null,
    @Json(name = "lastModifierId")
    val lastModifierId: java.util.UUID? = null,
    /* Created date */
    @Json(name = "createdAt")
    val createdAt: kotlin.String? = null,
    /* Date modified */
    @Json(name = "modifiedAt")
    val modifiedAt: kotlin.String? = null
) 



