/**
* Muisti API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package fi.metatavu.muisti.api.client.apis

import fi.metatavu.muisti.api.client.models.Error
import fi.metatavu.muisti.api.client.models.ExhibitionDeviceGroup

import fi.metatavu.muisti.api.client.infrastructure.ApiClient
import fi.metatavu.muisti.api.client.infrastructure.ClientException
import fi.metatavu.muisti.api.client.infrastructure.ClientError
import fi.metatavu.muisti.api.client.infrastructure.ServerException
import fi.metatavu.muisti.api.client.infrastructure.ServerError
import fi.metatavu.muisti.api.client.infrastructure.MultiValueMap
import fi.metatavu.muisti.api.client.infrastructure.RequestConfig
import fi.metatavu.muisti.api.client.infrastructure.RequestMethod
import fi.metatavu.muisti.api.client.infrastructure.ResponseType
import fi.metatavu.muisti.api.client.infrastructure.Success
import fi.metatavu.muisti.api.client.infrastructure.toMultiValue

class ExhibitionDeviceGroupsApi(basePath: kotlin.String = "http://localhost") : ApiClient(basePath) {

    /**
    * Create a device group
    * Creates new exhibition device group
    * @param exhibitionId exhibition id 
    * @param exhibitionDeviceGroup Payload 
    * @return ExhibitionDeviceGroup
    * @throws UnsupportedOperationException If the API returns an informational or redirection response
    * @throws ClientException If the API returns a client error response
    * @throws ServerException If the API returns a server error response
    */
    @Suppress("UNCHECKED_CAST")
    @Throws(UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun createExhibitionDeviceGroup(exhibitionId: java.util.UUID, exhibitionDeviceGroup: ExhibitionDeviceGroup) : ExhibitionDeviceGroup {
        val localVariableBody: kotlin.Any? = exhibitionDeviceGroup
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        val localVariableConfig = RequestConfig(
            RequestMethod.POST,
            "/exhibitions/{exhibitionId}/deviceGroups".replace("{"+"exhibitionId"+"}", "$exhibitionId"),
            query = localVariableQuery,
            headers = localVariableHeaders
        )
        val localVarResponse = request<ExhibitionDeviceGroup>(
            localVariableConfig,
            localVariableBody
        )

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ExhibitionDeviceGroup
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> throw ClientException((localVarResponse as ClientError<*>).body as? String ?: "Client error")
            ResponseType.ServerError -> throw ServerException((localVarResponse as ServerError<*>).message ?: "Server error")
        }
    }

    /**
    * Deletes device group.
    * Delets exhibition device group.
    * @param exhibitionId exhibition id 
    * @param deviceGroupId device group id 
    * @return void
    * @throws UnsupportedOperationException If the API returns an informational or redirection response
    * @throws ClientException If the API returns a client error response
    * @throws ServerException If the API returns a server error response
    */
    @Throws(UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun deleteExhibitionDeviceGroup(exhibitionId: java.util.UUID, deviceGroupId: java.util.UUID) : Unit {
        val localVariableBody: kotlin.Any? = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        val localVariableConfig = RequestConfig(
            RequestMethod.DELETE,
            "/exhibitions/{exhibitionId}/deviceGroups/{deviceGroupId}".replace("{"+"exhibitionId"+"}", "$exhibitionId").replace("{"+"deviceGroupId"+"}", "$deviceGroupId"),
            query = localVariableQuery,
            headers = localVariableHeaders
        )
        val localVarResponse = request<Any?>(
            localVariableConfig,
            localVariableBody
        )

        return when (localVarResponse.responseType) {
            ResponseType.Success -> Unit
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> throw ClientException((localVarResponse as ClientError<*>).body as? String ?: "Client error")
            ResponseType.ServerError -> throw ServerException((localVarResponse as ServerError<*>).message ?: "Server error")
        }
    }

    /**
    * Find a device group
    * Finds a device group by id
    * @param exhibitionId exhibition id 
    * @param deviceGroupId device group id 
    * @return ExhibitionDeviceGroup
    * @throws UnsupportedOperationException If the API returns an informational or redirection response
    * @throws ClientException If the API returns a client error response
    * @throws ServerException If the API returns a server error response
    */
    @Suppress("UNCHECKED_CAST")
    @Throws(UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun findExhibitionDeviceGroup(exhibitionId: java.util.UUID, deviceGroupId: java.util.UUID) : ExhibitionDeviceGroup {
        val localVariableBody: kotlin.Any? = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        val localVariableConfig = RequestConfig(
            RequestMethod.GET,
            "/exhibitions/{exhibitionId}/deviceGroups/{deviceGroupId}".replace("{"+"exhibitionId"+"}", "$exhibitionId").replace("{"+"deviceGroupId"+"}", "$deviceGroupId"),
            query = localVariableQuery,
            headers = localVariableHeaders
        )
        val localVarResponse = request<ExhibitionDeviceGroup>(
            localVariableConfig,
            localVariableBody
        )

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ExhibitionDeviceGroup
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> throw ClientException((localVarResponse as ClientError<*>).body as? String ?: "Client error")
            ResponseType.ServerError -> throw ServerException((localVarResponse as ServerError<*>).message ?: "Server error")
        }
    }

    /**
    * List device groups
    * List exhibition device groups
    * @param exhibitionId exhibition id 
    * @return kotlin.Array<ExhibitionDeviceGroup>
    * @throws UnsupportedOperationException If the API returns an informational or redirection response
    * @throws ClientException If the API returns a client error response
    * @throws ServerException If the API returns a server error response
    */
    @Suppress("UNCHECKED_CAST")
    @Throws(UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun listExhibitionDeviceGroups(exhibitionId: java.util.UUID) : kotlin.Array<ExhibitionDeviceGroup> {
        val localVariableBody: kotlin.Any? = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        val localVariableConfig = RequestConfig(
            RequestMethod.GET,
            "/exhibitions/{exhibitionId}/deviceGroups".replace("{"+"exhibitionId"+"}", "$exhibitionId"),
            query = localVariableQuery,
            headers = localVariableHeaders
        )
        val localVarResponse = request<kotlin.Array<ExhibitionDeviceGroup>>(
            localVariableConfig,
            localVariableBody
        )

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as kotlin.Array<ExhibitionDeviceGroup>
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> throw ClientException((localVarResponse as ClientError<*>).body as? String ?: "Client error")
            ResponseType.ServerError -> throw ServerException((localVarResponse as ServerError<*>).message ?: "Server error")
        }
    }

    /**
    * Updates device group.
    * Updates device group.
    * @param exhibitionId exhibition id 
    * @param deviceGroupId device group id 
    * @param exhibitionDeviceGroup Payload 
    * @return ExhibitionDeviceGroup
    * @throws UnsupportedOperationException If the API returns an informational or redirection response
    * @throws ClientException If the API returns a client error response
    * @throws ServerException If the API returns a server error response
    */
    @Suppress("UNCHECKED_CAST")
    @Throws(UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun updateExhibitionDeviceGroup(exhibitionId: java.util.UUID, deviceGroupId: java.util.UUID, exhibitionDeviceGroup: ExhibitionDeviceGroup) : ExhibitionDeviceGroup {
        val localVariableBody: kotlin.Any? = exhibitionDeviceGroup
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        val localVariableConfig = RequestConfig(
            RequestMethod.PUT,
            "/exhibitions/{exhibitionId}/deviceGroups/{deviceGroupId}".replace("{"+"exhibitionId"+"}", "$exhibitionId").replace("{"+"deviceGroupId"+"}", "$deviceGroupId"),
            query = localVariableQuery,
            headers = localVariableHeaders
        )
        val localVarResponse = request<ExhibitionDeviceGroup>(
            localVariableConfig,
            localVariableBody
        )

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ExhibitionDeviceGroup
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> throw ClientException((localVarResponse as ClientError<*>).body as? String ?: "Client error")
            ResponseType.ServerError -> throw ServerException((localVarResponse as ServerError<*>).message ?: "Server error")
        }
    }

}
