name: Build APK (master)
on:
  push:
    branches:
      - master
      - feature-199-app-updater
jobs:
  build:
    runs-on: ubuntu-latest
    environment: master
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 8

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build APK
        run: |
          echo ${{ secrets.SIGN_KEYSTORE }} > /tmp/upload-keystore.b64 && base64 -d -i /tmp/upload-keystore.b64 > /tmp/upload-keystore.jks
          echo SIGN_STORE_PASSWORD=${{ secrets.SIGN_STORE_PASSWORD }} >> ~/.gradle/gradle.properties
          echo SIGN_KEY_ALIAS=${{ secrets.SIGN_KEY_ALIAS }} >> ~/.gradle/gradle.properties
          echo SIGN_KEY_PASSWORD=${{ secrets.SIGN_KEY_PASSWORD }} >> ~/.gradle/gradle.properties
          echo SIGN_STORE_FILE=/tmp/upload-keystore.jks >> ~/.gradle/gradle.properties
          echo MUISTI_API_BASE_URL=${{ secrets.MUISTI_API_BASE_URL }} >> app/.env
          echo KEYCLOAK_URL=${{ secrets.KEYCLOAK_URL }} >> app/.env
          echo MQTT_BASE_TOPIC=${{ secrets.MQTT_BASE_TOPIC }} >> app/.env
          echo KEYCLOAK_REALM=${{ secrets.KEYCLOAK_REALM }} >> app/.env
          echo KEYCLOAK_CLIENT_ID=${{ secrets.KEYCLOAK_CLIENT_ID }} >> app/.env
          echo KEYCLOAK_USERNAME=${{ secrets.KEYCLOAK_USERNAME }} >> app/.env
          echo KEYCLOAK_PASSWORD=${{ secrets.KEYCLOAK_PASSWORD }} >> app/.env
          echo KEYCLOAK_DEMO_TAG=${{ secrets.KEYCLOAK_DEMO_TAG }} >> app/.env
          echo DESTRUCTIVE_MIGRATIONS=${{ secrets.DESTRUCTIVE_MIGRATIONS }} >> app/.env
          echo MQTT_BASE_URL=${{ secrets.MQTT_BASE_URL }} >> app/.env
          echo MQTT_PASSWORD=${{ secrets.MQTT_PASSWORD }} >> app/.env
          echo MQTT_USER=${{ secrets.MQTT_USER }} >> app/.env
          echo MAP_BOX_ACCESS_TOKEN=${{ secrets.MAP_BOX_ACCESS_TOKEN }} >> app/.env
          ./gradlew assembleRelease

      - name: Upload APK
        uses: shallwefootball/s3-upload-action@master
        with:
          aws_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_bucket: ${{ secrets.UPDATES_BUCKET }}
          source_dir: app/build/outputs/apk/release/
          destination_dir: ""