name: Build APK (master)
on:
  push:
    branches:
      - master
      - feature-199-app-updater
jobs:
  build:
    runs-on: ubuntu-latest
    environment: master
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 8

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build APK
        run: ./gradlew assemble